#if !defined MAX_PLAYERS
#define MAX_PLAYERS             32
#endif

#if !defined MAX_NAME_LENGTH
#define MAX_NAME_LENGTH         32
#endif

#if !defined MAX_AUTHID_LENGTH 
#define MAX_AUTHID_LENGTH       35
#endif

#if !defined MAX_IP_LENGTH
#define MAX_IP_LENGTH           17
#endif

#define MAX_DATE_LENGTH         22
#define MAX_FLAGS_LENGTH        27
#define MAX_PASSWORD_LENGTH     32
#define MAX_CONFIGS_LENGTH      64
#define MAX_MAP_NAME_LENGTH     32
#define MAX_TEXT_LENGTH         192
#define MAX_REASON_LENGTH       64

#define g_szConfigFile "EliteAdminSystem_Config.cfg"