#if defined _reno_acc_keys_included
    #endinput
#endif

#define _reno_acc_keys_included

/**
 * Auth Access Keys.
 */
stock const AUTH_KEY_DEFAULT    = 920;
stock const AUTH_KEY_USERNAME   = 921;
stock const AUTH_KEY_VIPCLASS   = 922;
stock const AUTH_KEY_STEAMID    = 923;


/**
 * Misc Access Keys.
 */
// TODO: Rename this constants !!!
const FEAT_ACCESS_NONE    = 101;
const FEAT_ACCESS_ALL     = 111;
const FEAT_ACCESS_VIPS    = 777;
const FEAT_ACCESS_PREMIUM   = 888;
