name: Compile AMXX Plugins

on:
  push:
    paths:
      - 'Source/**/*.sma'
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install json5

      - name: Install Required 32-bit Libraries
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y lib32gcc1 libc6:i386

      - name: Set Execute Permissions for AMXX Compiler
        run: chmod +x Compiler/*/amxxpc || true

      - name: Verify `amxxpc32.so` Library
        run: |
          find Compiler -name "amxxpc32.so" || echo "Library not found!"
          ldd Compiler/*/amxxpc || true

      - name: Run Compilation Script
        run: python compile_amxx.py

      - name: Commit and Push Updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add Updates.json Compiled/ || true
          git diff --cached --quiet || (git commit -m "Automated compilation update" && git push)
